#!/usr/bin/env bash
cd test/tests-p3/rc_charge
source rc_charge_demo.sh
cd ../rc_discharge/
source rc_discharge_demo.sh
cd ../rl_charge/
source rl_charge_demo.sh
cd ../rl_discharge/
source rl_discharge_demo.sh
cd ../sine_source/
source sine_source_demo.sh
cd ../pwl_source/
source pwl_source_demo.sh